name: inventory-dev

services:
  app:
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: development
      # Ensure dev app points to a dev-specific DB name
      DATABASE_URL: mysql://inventory:${MYSQL_PASSWORD}@db:3306/inventory_dev?connection_limit=20
    ports:
      - "3000:3000"
    networks:
      - internal
    labels: {}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    environment:
      # Ensure migrations target the dev schema
      DATABASE_URL: mysql://inventory:${MYSQL_PASSWORD}@db:3306/inventory_dev?connection_limit=20

  db:
    volumes:
      - db_data_dev:/var/lib/mysql
    environment:
      # Use a different schema name for dev to avoid any confusion
      MYSQL_DATABASE: inventory_dev

  backup:
    profiles: ["never"]
    environment:
      MYSQL_DB: inventory_dev

networks:
  internal:
    driver: bridge

volumes:
  db_data_dev:
